[package]
name = "server"
version = "0.1.0"
authors = ["Ted Zilist <ted@goop.com>"]
edition = "2018"

[lib]
name = "server"
path = "src/lib.rs"

[dependencies]
actix-web = "2.0"
config = { package = "config", path = "../config" }
log = "0.4"
