[package]
name = "bin"
version = "0.1.0"
authors = ["Ted Zilist <tzilist@gmail.com>"]
edition = "2018"

[[bin]]
name = "csv_parser"
path = "src/main.rs"

[dependencies]
actix-rt = "1.1"
config = { package = "config", path = "../config" }
log = "0.4"
server = { package = "server", path = "../server" }
tokio = { version = "0.2", features = ["full"] }

